package com.android.burdacontractor.feature.suratjalan.domain.model

data class AllSuratJalan(
    val id: String? = null,
    val alamatTempatTujuan: String? = null,
    val coordinateTempatAsal: String? = null,
    val namaAdminGudang: String? = null,
    val fotoDriver: String? = null,
    val coordinateTempatTujuan: String? = null,
    val alamatTempatAsal: String? = null,
    val namaTempatTujuan: String? = null,
    val updatedAt: Long? = null,
    val namaTempatAsal: String? = null,
    val fotoProjectManager: String? = null,
    val kodeSurat: String? = null,
    val namaDriver: String? = null,
    val fotoAdminGudang: String? = null,
    val namaProjectManager: String? = null,
    val status: String? = null,
    val tipe: String? = null,
    val namaSupervisor: String? = null,
    val fotoSupervisor: String? = null,
    val namaSupervisorPeminjam: String? = null,
    val fotoSupervisorPeminjam: String? = null,
)