@startuml
'https://plantuml.com/class-diagram

class burdacontracor.core.domain.usecase.SuratJalanInteractor implements burdacontracor.core.domain.usecase.SuratJalanUseCase
class burdacontracor.core.data.source.remote.SuratJalanRemoteDataSource
class burdacontracor.core.data.source.remote.SuratJalanRemoteDataSource
interface burdacontracor.core.domain.usecase.SuratJalanUseCase
interface burdacontracor.core.domain.repository.ISuratJalanRepository
interface burdacontracor.core.data.source.remote.network.SuratJalanService
class burdacontracor.core.data.SuratJalanRepository implements burdacontracor.core.domain.repository.ISuratJalanRepository
burdacontracor.core.data.SuratJalanRepository -u> burdacontracor.core.data.source.remote.SuratJalanRemoteDataSource
burdacontracor.core.data.SuratJalanRepository -u> burdacontracor.core.data.source.remote.StorageDataSource
burdacontracor.core.domain.usecase.SuratJalanInteractor -d> burdacontracor.core.data.SuratJalanRepository
burdacontracor.presentation.suratjalan.SuratJalanViewModel -l> burdacontracor.core.domain.usecase.SuratJalanUseCase
burdacontracor.core.data.source.remote.SuratJalanRemoteDataSource -l> burdacontracor.core.data.source.remote.network.SuratJalanService
class burdacontracor.presentation.suratjalan.SuratJalanViewModel<HiltViewModel> {
    +state
    +allSuratJalanResponse: LiveData<AllSuratJalanResponse>
    +suratJalanDetailResponse: LiveData<AllSuratJalanResponse>
    +pantauSuratJalanResponse
    +messageResponse
    +getAllSuratJalan()
    +getSuratJalanById()
    +addSuratJalanPengirimanPp()
    +addSuratJalanPengembalian()
    +updateSuratJalanPengirimanGp()
    +updateSuratJalanPengirimanGp()
    +updateSuratJalanPengembalian()
    +deleteSuratJalan()
    +changeStatusSuratJalan()
    +uploadFotoBukti()
    +pantauSuratJalan()
    +telusuriSuratJalan()
}
class burdacontracor.presentation.suratjalan.SuratJalanActivity{
    -binding
    onCreate()
    onNavigationItemSelected()
}
class burdacontracor.presentation.suratjalan.SuratJalanFragment{
    -binding
    onCreateView()
    onViewCreated()
    validateAddSuratJalan()
    validateAddSuratJalan()

}
class SuratJalanCreateFragment{
    -binding
    -navController
    -suratJalanViewModel
    -logisticViewModel
    initListener()
    addSuratJalan()
    onNavigationItemSelected()
}

class SessionManager {
    -pref
    -editor
    +KEY_LOGIN
    +KEY_TOKEN
    +KEY_USER_ID
    +KEY_ROLE
    +createLoginSession()
    +logout()
    +isLogin()
    +saveToPreference()
    +getFromPreference()
}

abstract NetworkModule<SingletonComponent> {
    +provideFirebaseReference()
    +provideConnectivityManager()
    +provideOkHttpClient()
    +provideDistanceMatrixService()
    +provideRetrofit()
    +provideApiService()
    +provideAuthService()
    +provideUserService()
    +provideBarangService()
    +provideDeliveryOrderService()
    +provideProyekService()
    +providePerusahaanService()
    +provideGudangService()
    +providePeminjamanService()
    +providePengembalianService()
    +provideAksesBarangService()
    +provideKendaraanService()
    +providePreOrderService()
    +provideSuratJalanService()
}
abstract StorageModule<SingletonComponent> {
    +provideSessionManager()
}

abstract RepositoryModule<SingletonComponent> {
    +provideSuratJalanRepository()
    +provideTourismRepository()
    +provideLogisticRepository()
    +provideLogisticRepository()
    +provideStorageRepository()
    +provideKendaraanRepository()
    +providePeminjamanRepository()
    +providePengembalianRepository()
    +providePerusahaanRepository()
    +provideGudangRepository()
    +provideProyekRepository()
    +provideBarangRepository()
    +provideAksesBarangRepository()
    +provideDeliveryOrderRepository()
}
abstract AppModule<ViewModelComponent> {
    +provideTourismUseCase()
    +provideSuratJalanUseCase()
    +provideAuthUseCase()
    +provideLogisticUseCase()
    +provideStorageUseCase()
    +provideKendaraanUseCase()
    +providePeminjamanUseCase()
    +providePengembalianUseCase()
    +providePerusahaanUseCase()
    +provideGudangUseCase()
    +provideProyekUseCase()
    +provideBarangUseCase()
    +provideAksesBarangUseCase()
    +provideDeliveryOrderUseCase()
    +providePreOrderUseCase()
    +provideUserUseCase()
    +provideDistanceMatrixUseCase()
}

class AuthViewModel<HiltViewModel> {
    +loginResponse
    +messageResponse
    +state
    +loginUser()
    +loginWithPin()
    +register()
    +logout()
}

class UserViewModel<HiltViewModel>{
    +profileResponse
    +ttd
    +messageResponse
    +state
    +getProfile()
    +updateProfile()
    +updatePassword()
    +uploadPhoto()
    +uploadTTD()
    +getTTD()
}

class DeliveryOrderViewModel<HiltViewModel> {
    +state
    +allDeliveryOrderResponse
    +deliveryOrderDetailResponse
    +pantauDeliveryOrderResponse
    +messageResponse
    +getAllDeliveryOrder()
    +getDeliveryOrderById()
    +addDeliveryOrder()
    +deleteDeliveryOrder()
    +changeStatusDeliveryOrder()
    +uploadFotoBukti()
    +pantauDeliveryOrder()
}

class PerusahaanViewModel<HiltViewModel> {
    +state
    +allPerusahaanResponse
    +perusahaanDetailResponse
    +messageResponse
    +getAllPerusahaan()
    +getPerusahaanById()
    +addPerusahaan()
    +deletePerusahaan()
    +updatePerusahaan()
}

class GudangViewModel<HiltViewModel> {
    +state
    +allGudangResponse
    +gudangDetailResponse
    +messageResponse
    +getAllGudang()
    +getGudangById()
    +addGudang()
    +deleteGudang()
    +updateGudang()
    +tempatiGudang()
}

class KendaranViewModel<HiltViewModel> {
    +state
    +allKendaraanResponse
    +kendaraanDetailResponse
    +messageResponse
    +getAllKendaraan()
    +getKendaraanById()
    +addKendaraan()
    +deleteKendaraan()
    +updateKendaraan()
    +hapusPengendara()
}

enum UserRole {
ADMIN
ADMIN_GUDANG
SUPERVISOR
LOGISTIC
PURCHASING
PROJECT_MANAGER
UMUM
}

enum SuratJalanStatus {
    MENUNGGU_KONFIRMASI_DRIVER
    DRIVER_DALAM_PERJALANAN
    SELESAI
}

enum PengembalianStatus {
    MENUNGGU_PENGEMBALIAN
    SEDANG_DIKEMBALIKAN
    SELESAI
}
enum PeminjamanTipe {
    GUDANG_PROYEK
    PROYEK_PROYEK
}
enum SuratJalanTipe {
    PENGIRIMAN_PROYEK_PROYEK
    PENGIRIMAN_GUDANG_PROYEK
    PENGEMBALIAN
}
enum PeminjamanStatus {
    MENUNGGU_AKSES
    AKSES_DITOLAK
    MENUNGGU_PENGIRIMAN
    SEDANG_DIKIRIM
    DIPINJAM
    SELESAI
}

enum PeminjamanDetailStatus {
    MENUNGGU_AKSES
    DIGUNAKAN
    TIDAK_DIGUNAKAN
    DIPINJAM_PROYEK_LAIN
    DIKEMBALIKAN
}

enum BarangTidakHabisPakaiKondisi {
    BARU
    BEKAS
}

enum DeliveryOrderStatus {
    MENUNGGU_KONFIRMASI_ADMIN_GUDANG
    MENUNGGU_KONFIRMASI_DRIVER
    DRIVER_DALAM_PERJALANAN
    SELESAI
}

@enduml