@startuml
'https://plantuml.com/class-diagram

header App Package

package "app" {
    package "src" {

    }
    package "res" {

    }
}
newpage
header Source Package
package "src" {
    package "core"{

    }
    package "presentation"{

    }
}
newpage
header Core Package
package "core"{
    package "domain"{

    }
    package "data"{

    }
    package "di"{

    }
    package "ui"{

    }
    package "utils"{

    }
}
newpage
header Domain Package
package "domain"{
    package "model"{

    }
    package "repository"{

    }
    package "usecase"{

    }
}
newpage
header User Interface Package
package "ui"{
    package "adapter"{

    }
    package "customview"{

    }
}
newpage
header Utility Package
package "utils"{

}
newpage
header Presentation Package
package "presentation"{
    package "Activity/Fragment"{

    }
    package "viewmodel"{

    }
}

newpage
header Resource Package
package "res" {
    package "drawable"{

    }
    package "layout"{

    }
    package "font"{

    }
    package "menu"{

    }
    package "navigation"{

    }
    package "mipmap"{

    }
    package "color"{

    }
    package "values"{

    }
}

newpage
header Surat Jalan Class Diagram
class src.core.domain.usecase.SuratJalanInteractor implements src.core.domain.usecase.SuratJalanUseCase
class src.core.data.source.remote.SuratJalanRemoteDataSource
class src.core.data.source.remote.SuratJalanRemoteDataSource
interface src.core.domain.usecase.SuratJalanUseCase
interface src.core.domain.repository.ISuratJalanRepository
interface src.core.data.source.remote.network.SuratJalanService
class src.core.data.SuratJalanRepository implements src.core.domain.repository.ISuratJalanRepository
src.core.data.SuratJalanRepository -u> src.core.data.source.remote.SuratJalanRemoteDataSource
src.core.data.SuratJalanRepository -> src.core.data.source.remote.StorageDataSource
src.core.domain.usecase.SuratJalanInteractor --d> src.core.data.SuratJalanRepository
src.presentation.suratjalan.SuratJalanViewModel --d> src.core.domain.usecase.SuratJalanUseCase
src.core.data.source.remote.SuratJalanRemoteDataSource -l> src.core.data.source.remote.network.SuratJalanService
class src.presentation.suratjalan.SuratJalanViewModel<HiltViewModel> {
    +state
    +allSuratJalanResponse: LiveData<AllSuratJalanResponse>
    +suratJalanDetailResponse: LiveData<AllSuratJalanResponse>
    +pantauSuratJalanResponse
    +messageResponse
    +getAllSuratJalan()
    +getSuratJalanById()
    +addSuratJalanPengirimanPp()
    +addSuratJalanPengembalian()
    +updateSuratJalanPengirimanGp()
    +updateSuratJalanPengirimanGp()
    +updateSuratJalanPengembalian()
    +deleteSuratJalan()
    +changeStatusSuratJalan()
    +uploadFotoBukti()
    +pantauSuratJalan()
    +telusuriSuratJalan()
}
@enduml