@startuml
'https://plantuml.com/sequence-diagram

group Admin Gudang Hapus SuratJalan
    actor       AdminGudang
    boundary    fragment_detail_surat_jalan
    control     DetailSuratJalanFragment

    AdminGudang -> fragment_detail_surat_jalan : 1. Click icon delete
    activate fragment_detail_surat_jalan

    fragment_detail_surat_jalan -> DetailSuratJalanFragment : 2. deleteSuratJalan()
    deactivate fragment_detail_surat_jalan

    activate DetailSuratJalanFragment
    DetailSuratJalanFragment -> SuratJalanViewModel : 3. deleteSuratJalan()
    activate SuratJalanViewModel
    SuratJalanViewModel -> SuratJalanViewModel : 4.1 <<Response.Success>>
    activate SuratJalanViewModel
    DetailSuratJalanFragment <-- SuratJalanViewModel
    AdminGudang <-- DetailSuratJalanFragment :  <font color=green>Mendapatkan pesan berhasil hapus surat jalan
    deactivate SuratJalanViewModel

    SuratJalanViewModel -> SuratJalanViewModel : 4.2 <<Response.Error>>
    activate SuratJalanViewModel

    DetailSuratJalanFragment <-- SuratJalanViewModel

    deactivate SuratJalanViewModel
    deactivate SuratJalanViewModel

    AdminGudang <-- DetailSuratJalanFragment : <font color=red>Mendapatkan pesan error hapus surat jalan

end
@enduml