@startuml
'https://plantuml.com/sequence-diagram

group Admin Gudang Ubah Kendaraan
    actor       AdminGudang
    boundary    fragment_detail_kendaran
    control     DetailKendaraanFragment
    boundary    fragment_update_kendaran
    control     UpdateKendaraanFragment

    AdminGudang -> fragment_detail_kendaran : 1. Click tombol ubah kendaran

    activate fragment_detail_kendaran
    fragment_detail_kendaran -> DetailKendaraanFragment : 2. navigateToUpdateKendaraan()
    deactivate fragment_detail_kendaran

    activate DetailKendaraanFragment
    DetailKendaraanFragment -> fragment_update_kendaran
    deactivate DetailKendaraanFragment
    activate fragment_update_kendaran
    fragment_update_kendaran -> UpdateKendaraanFragment : 3. onCreateView()
    activate UpdateKendaraanFragment
    AdminGudang -> fragment_update_kendaran : 4. Mengubah data kendaran
    fragment_update_kendaran -> UpdateKendaraanFragment : 5. validateUpdateKendaraan()
    deactivate fragment_update_kendaran

    UpdateKendaraanFragment -> KendaraanViewModel : 6. updateKendaraan()
    activate KendaraanViewModel
    KendaraanViewModel -> KendaraanViewModel : 7.1 <<Response.Success>>
    activate KendaraanViewModel
    UpdateKendaraanFragment <-- KendaraanViewModel
    deactivate KendaraanViewModel
    activate UpdateKendaraanFragment
    AdminGudang <-- UpdateKendaraanFragment :  <font color=green>Mendapatkan pesan berhasil ubah kendaran
    activate AdminGudang
    deactivate AdminGudang
    deactivate UpdateKendaraanFragment

    KendaraanViewModel -> KendaraanViewModel : 7.2 <<Response.Error>>
    activate KendaraanViewModel

    UpdateKendaraanFragment <-- KendaraanViewModel

    deactivate KendaraanViewModel
    deactivate KendaraanViewModel
    activate UpdateKendaraanFragment
    AdminGudang <-- UpdateKendaraanFragment : <font color=red>Mendapatkan pesan error ubah kendaran
    activate AdminGudang
    deactivate AdminGudang
    deactivate UpdateKendaraanFragment
end
@enduml